### ISSUE TITLE
'beSupersetOf' fails to compare mutable collection with immutable one

### ISSUE THREAD

**Issue by bwaresiak** [specta/expecta#110]
Example:

        NSString *string = @"Test";
        NSArray *arrA = @[string];
        NSArray *arrB = @[string];
        
        expect(arrA).to.beSupersetOf(arrB);
            
        NSMutableArray *arrAm = [arrB mutableCopy];
        expect(arrAm).to.beSupersetOf(arrB);   //  this fails

Result is an error: (Test) does not match the class of (Test) , which is obvious.

Looking inside debugger:

    (lldb) po actual
    <__NSArrayM 0xe187910>(
    Test
    )
    (lldb) po subset
    <__NSArrayI 0xe17e820>(
    Test
    )

Is this me, that is using this in an incorrect way, or actually a bug?

Also, IMHO, error is not really meaningful, as for big collections it prints load of useless info (collection contents) when the point of this message is about subset/actual class types.

Thanks!

**Comment by mmiroslav** [comment]
I'm face the same problem.
Workaround would be something like this:
 ` expect([arrAm copy]).to.beSupersetOf([arrB copy]);`
