### ISSUE TITLE
Changelog entry for v0.3.1

### ISSUE THREAD

**Issue by mickeyreiss** [specta/expecta#115]
I can't seem to find any info in the [CHANGELOG](https://github.com/specta/expecta/blob/60388f9dec0292bf8e45c120f43515c52b6ca507/CHANGELOG.md) about the v0.3.1 release.

**Comment by orta** [comment]
I have updated the CHANGELOGs: https://github.com/specta/expecta/commit/40c8ca3a91fd5b7766e6fe5a94e7f882fba86aef
