### ISSUE TITLE
False negative result when comparing NSNumber to NSDecimalNumber with .equal()

### ISSUE THREAD

**Issue by rolandkakonyi** [specta/expecta#118]
NSNumber *expectedNumber = @1.07;
NSDecimalNumber *numberUnderTest = [NSDecimalNumber decimalNumberWithString:@"1.07"

//this fails (because of comparing float values in .equal() method)
expect(numberUnderTest).to.equal(expectedNumber);

//this succeeds
XCTAssert([numberUnderText isEqualToNumber:[[NSDecimalNumber alloc] initWithDecimal:[expectedNumber decimalValue]]], @"numbers are not equal");

When comparing NSDecimalNumber with NSNumber an NSDecimalNumber should be initialised from the NSNumber for the comparison.

**Comment by orta** [comment]
Thanks! merged. Closing.
