### ISSUE TITLE
build error while using expecta

### ISSUE THREAD

**Issue by zixun** [specta/expecta#120]
i add expecta to my project by cocoapods
 ```ruby
target :"ZXUnitTestTutorialTests", :exclusive => true do
    pod 'OCMock', '~> 3.1.1'
    pod 'Kiwi', '~> 2.3.1'
    pod 'Expecta',  '~> 0.2.4'
end
 ```
but while i bulid my project i got an error like this:
![127b591a-4ceb-4394-bb6c-12334135d03c](https://cloud.githubusercontent.com/assets/6824547/5043041/dc2a23a4-6c1b-11e4-9e14-c86fb6d85ac1.png)

**Comment by orta** [comment]
Just done this with the latest setup, compiles fine:

```
target 'demo' do
end

target 'demoTests' do
  pod 'OCMock', '~> 3.1'
  pod 'Kiwi', '~> 2.3'
  pod 'Expecta',  '~> 0.2'
end
```
