### ISSUE TITLE
Tests succeeded while failed

### ISSUE THREAD

**Issue by henkvanderspek** [specta/expecta#122]
I would expect this to fail my test, but it doesn't:

```
it(@"tests something", ^{
        BOOL succeeded = NO;
        expect(succeeded).to.beTruthy();
}
```

**Comment by orta** [comment]
Are you sure this is happening still? We have tests specifically covering this, that pass:

```
  assertFail(test_expect(NO).beTruthy(), @"expected: a truthy value, got: 0, which is falsy");
  assertFail(test_expect(FALSE).beTruthy(), @"expected: a truthy value, got: 0, which is falsy");
```

**Comment by asm09fsu** [comment]
@henkvanderspek 's code works fine for me, but it seems as though when doing inline logical evaluations it fails.

```objective-c        
    BOOL eval = YES && NO;
    expect(eval).to.beFalsy; // Should succeed. It does.
    expect(eval).to.beTruthy; // Should fail. It doesn't.
    expect(YES && NO).to.beTruthy; // Should fail. It doesn't.
````

It seems although if we use equal() instead of isTruthy/Falsy, we get the correct responses
```objective-c
    expect(eval).to.equal(NO); // Should succeed. It does.
    expect(eval).to.equal(YES); // Should fail. It does.
````

I just pulled down a zipped version of Expecta about 10 minutes ago, and ran these tests, so it shouldn't be that my library is out of date.

**Comment by henkvanderspek** [comment]
I haven't really checked it yet. But anybody can, that's why I've embedded the code sample. I do have a lot of question/problems regarding Xcode integration, but will post a new issue for that.

**Comment by orta** [comment]
There should always be a `()` at the end of the `beTruthy` / `beFalsy`. I also though this was fixed.

**Comment by robb** [comment]
> However, in other instances outside of this one, not using () returns the correct expect. This may be a bug? I'm not sure.

The matchers are never evaluated without the `()`, since that's what actually evaluating them. So `expect(true).to.beTruthy;` won't do anything, but since it's a tautology, it won't fail the spec either way.

**Comment by orta** [comment]
Closing, I don't think there's much actionable we can do further.
