### ISSUE TITLE
Universal build not generated

### ISSUE THREAD

**Issue by andres-ciano** [specta/expecta#135]
According to the doc to manually setup Expecta, a `build/Release-ios-universal` path is created with the universal lib.
It seems it is not doing so, and only the `iphoneos` and `iphonesimulator` are created.

If it helps anybody with this issue, in order to do so, lipo can be used from /expecta/build:
`lipo -create -output ./libExpecta.a ./Release-iphoneos/libExpecta.a ./Release-iphonesimulator/libExpecta.a`

**Comment by tonyarnold** [comment]
Hi @andres-ciano it looks like `master` currently requires the use of `xcpretty` as part of its build scripts. We're looking at making that optional, but in the meantime installing the `xcpretty` tool should generate the universal libraries you need. Sorry about this!

**Comment by jmoody** [comment]
@tonyarnold 

I think the README is incorrect.

The final destination for the framework is `Products/ios/Expecta.framework`.

Locally, I am seeing universal binaries created:

```
$ lipo -info Products/ios/Expecta.framework/Expecta 
Architectures in the fat file: Products/ios/Expecta.framework/Expecta are: i386 x86_64 armv7 arm64 
$ lipo -info Products/ios/libExpecta.a 
Architectures in the fat file: Products/ios/libExpecta.a are: armv7 i386 x86_64 arm64 
```

re: `xcpretty` I wondered about that.  I did see, however that the rake `test` task was using xcpretty already, so I made a bad assumption.

**Comment by jmoody** [comment]
@tonyarnold 

RE: the README - I will make a pull request on the README to show you where I think it is incorrect.

**Comment by orta** [comment]
This is merged, closing :+1:
