### ISSUE TITLE
`equal` failing without reason

### ISSUE THREAD

**Issue by esttorhe** [specta/expecta#138]
I'm trying to compare `NSDictionary` and its failing so I decided to break down the comparison by `key` like this:
```objc
NSDictionary *dict1 = @{ @"key": @"1" };
NSDictionary *dict2 = @{ @"key": @"1" };

expect(dict1[@"key"].to.equal(dict2[@"key"]));
```

But its failing saying
>expected: 1; got: 1

Same thing if I compare the 2 dictionaries directly I get
>expected: \<dictionary>; got: \<dictionary>

See attached image of the generated failure:
![screen_shot_2015-03-17_at_15_49_29](https://cloud.githubusercontent.com/assets/2642850/6698380/bd9a830e-ccbd-11e4-991c-897457cb3b0c.jpg)

**Comment by ollieatkinson** [comment]
What is your exact code? I have setup a basic test project with your example (fixing the compile errors) and it works fine.

```objective-c
#import <Specta/Specta.h>

#define EXP_SHORTHAND
#import <Expecta/Expecta.h>

SpecBegin(Test)

describe(@"NSDictionary comparison", ^{
  
  it(@"key to equal key", ^{
    
    NSDictionary *dict1 = @{ @"key": @"1" };
    NSDictionary *dict2 = @{ @"key": @"1" };
    
    expect(dict1[@"key"]).to.equal(dict2[@"key"]);
    
  });
  
});

SpecEnd
```

__output__

```
= TestSpec
      Test Suite 'TestSpec' started at 2015-03-17 23:17:41 +0000

      -[TestSpec NSDictionary_comparison_key_to_equal_key]
        Test Case '-[TestSpec NSDictionary_comparison_key_to_equal_key]' started.
        Test Case '-[TestSpec NSDictionary_comparison_key_to_equal_key]' passed (0.204 seconds).
      
      Test Suite 'TestSpec' finished at 2015-03-17 23:17:41 +0000.
      Executed 1 test, with 0 failures (0 unexpected) in 0.204 (0.205) seconds
```

**Comment by paulsamuels** [comment]
Are you comparing two objects that have the same `description` but are not equal e.g. comparing an `NSString` of value `@"1"` to an `NSNumber` of value `@1` will print the error message you have gotten.

**Comment by esttorhe** [comment]
@paulsamuels no; i'm comparing 2 `NSString` objects.
Actually I'm comparing full objects but since I was getting this weird bug I decided to break it into pieces to find where it was failing; sadly it is failing just at the simplest level.

---

@ollieatkinson here's the code:
```objc
it(@"converts a model back to its dictionary representation", ^{
  NSDictionary *userDictionary = @{
                                   kGAUserPublic: @"1",
                                   kGAUserEmail: @"test@email.com",
                                   kGAUserName: @"@username",
                                   kGAUserProfilePhotoUrl: @"tmp",
                                   kGAUserProfilePhotoMediumUrl: @"tmp",
                                   kGAUserProfilePhotoUrl: @"tmp",
                                   kGAUserFollowed: @"1",
                                   kGAUserUpdatedAt: @"tmp",
                                   kGAUserCoverPhotoUrl: @"tmp",
                                   kGAUserLastName: @"last_name",
                                   kGAUserName: @"name",
                                   kGAUserProfilePhotoFileSize: @"2.1",
                                   kGAUserType: @"type",
                                   kGAUserCoverPhotoMediumUrl: @"url",
                                   kGAUserEmailVerified: @"0",
                                   kGAUserId: @"1",
                                   kGAUserGender: @"male",
                                   kGAUserCoverPhotoFileName: @"name",
                                   kGAUserFollowersCount: @"5",
                                   kGAUserProfilePhotoFileName: @"name",
                                   kGAUserCoverPhotoContentType: @"tmp",
                                   kGAUserCoverPhotoUpdatedAt: @"tmp",
                                   kGAUserCoverPhotoFileSize: @"2.2",
                                   kGAUserProfilePhotoContentType: @"tmp",
                                   kGAUserCreatedAt: @"tmp",
                                   kGAUserFirstName: @"first_name"
                                   };
  
  GAUser *user = [GAUser modelObjectWithDictionary:userDictionary];
  NSDictionary *dictRep = [user dictionaryRepresentation];
  expect(dictRep).notTo.beNil();
  expect(dictRep[kGAUserFirstName]).to.equal(userDictionary[kGAUserFirstName]);
});
```

I think the methods are pretty straight forward; one converts an `NSDictionary` into a model and the other from the model back to `NSDictionary`

I'm comparing here `first_name` keys (which is stored in a constant `kGAUserFirstName` to avoid issues from miss typed key names).

_Edit: I pasted here the code with `NSString` due to @paulsamuels's comment to showcase that is throwing a weird error even with non numerical values_

**Comment by orta** [comment]
Which version of expecta are you on? I've tried running this on Expecta `0.3.2`

```
it(@"tests", ^{
    NSDictionary *dict = @{
       @"one": @"two"
   };
    expect(@"two").to.equal(dict[@"two"]);
});

it(@"tests 2", ^{
    NSDictionary *dict1 = @{ @"key": @"1" };
    NSDictionary *dict2 = @{ @"key": @"1" };

    expect(dict1[@"key"].to.equal(dict2[@"key"]));
});
```

and it passes each time

**Comment by esttorhe** [comment]
According to my `Podfile.lock`
>- Expecta (0.3.2)

I'll check again key by key and see if I can easily reproduce it

**Comment by robb** [comment]
Does `expect([dict1[@"key"] isEqual:dict2[@"key"]]).to.beTruthy();`pass?

**Comment by orta** [comment]
This passes:

```
- (void)test_NSDictionary
{
    NSDictionary *dict = @{ @"key": @"value" };
    expect(@"value").to.equal(dict[@"key"]);

    NSDictionary *dict1 = @{ @"key": @"1" };
    NSDictionary *dict2 = @{ @"key": @"1" };
    
    expect(dict1[@"key"]).to.equal(dict2[@"key"]);
    expect([dict1[@"key"] isEqual:dict2[@"key"]]).to.beTruthy();
}
```

I'm struggling to be able to replicate your use case.

**Comment by esttorhe** [comment]
Sorry for not replying back.

I think its safe to close this issue.
Apparently the code we were using to "parse" back from "JSON" (dictionary representation) and viceversa is treating one side as `NSString` and the other as `NSNumber`; thus making the whole thing fail.

When we print out both objects they all print exactly the same but the object classes are different.


Sorry for the confusion :see_no_evil:
