### ISSUE TITLE
`expect(nil).notTo.beNil;` doesn't fail

### ISSUE THREAD

**Issue by xareelee** [specta/expecta#149]
I tried the follow expectation:

```
expect(nil).toNot.beNil;
expect(nil).notTo.beNil;
expect(nil).to.beNil;
```

but all of them were not failed which first two should be.

**Comment by paulsamuels** [comment]
You are missing the parens to invoke the matcher `beNil` e.g.

`expect(nil).toNot.beNil()`

**Comment by xareelee** [comment]
Gosh! I'm so stupid that I didn't notice this. Maybe try to let the compiler complain this situation when this happens.

Thanks for your rapidly reply.
