### ISSUE TITLE
Integration notes update

### ISSUE THREAD

**Issue by lukewar** [specta/expecta#153]
I was integrating Expecta using Carthage with my old project. I was getting this error during compile time:
```Include of non-modular header inside framework module```
I think it would be worth mentioning that test target needs to have `Allow Non-modular Includes in Framework Modules` setting set to `YES`.

**Comment by orta** [comment]
Perhaps there's a way to fix Expecta so it doesn't need that in Carthage projects?

**Comment by lukewar** [comment]
Valid point.

**Comment by tonyarnold** [comment]
@lukewar could you get the full error that Xcode produces from your build logs and paste them back here please? It's definitely fixable in Expecta, but the logs will help pinpoint where the problem is.

**Comment by lukewar** [comment]
@tonyarnold sure. Here it is:
![expecta-build-error](https://cloud.githubusercontent.com/assets/7632110/8450854/e6404c0c-1fde-11e5-8b7c-eb5f02f1e88b.png)

**Comment by tonyarnold** [comment]
Thanks @lukewar, but I really need the text based build log from under the report navigator - the proper build log will tell me which file/line number the error happens at.

**Comment by lukewar** [comment]
Sorry, I am not in my best shape today :)

```
<PROJECT_PATH>/Carthage/Build/iOS/Expecta.framework/Headers/Expecta.h
<PROJECT_PATH>/Carthage/Build/iOS/Expecta.framework/Headers/Expecta.h:9:9: Include of non-modular header inside framework module 'Expecta'
<PROJECT_PATH>/Carthage/Build/iOS/Expecta.framework/Headers/Expecta.h:10:9: Include of non-modular header inside framework module 'Expecta'
<PROJECT_PATH>/<module-includes>
<PROJECT_PATH>/<module-includes>:1:1: Umbrella header for module 'Expecta' does not include header 'EXPBlockDefinedMatcher.h'
<PROJECT_PATH>/<module-includes>:1:1: Umbrella header for module 'Expecta' does not include header 'EXPDefines.h'
<PROJECT_PATH>/<module-includes>:1:1: Umbrella header for module 'Expecta' does not include header 'ExpectaObject.h'
<PROJECT_PATH>/<module-includes>:1:1: Umbrella header for module 'Expecta' does not include header 'ExpectaSupport.h'
<PROJECT_PATH>/<module-includes>:1:1: Umbrella header for module 'Expecta' does not include header 'EXPExpect.h'
<PROJECT_PATH>/<module-includes>:1:1: Umbrella header for module 'Expecta' does not include header 'EXPMatcher.h'
<PROJECT_PATH>/SpectaTest.m
<PROJECT_PATH>/SpectaTest.m:10:9: Could not build module 'Expecta'
```

**Comment by orta** [comment]
Assuming this isn't an issue anymore, or others would have raised it in the last year or so.
