### ISSUE TITLE
Compiler warnings on iOS9 / XCode 7

### ISSUE THREAD

**Issue by yakovsh** [specta/expecta#169]
Getting the following warnings when using Expecta in an application:

yakovsh/Downloads/expecta-1.0.3/build/ModuleCache/CE2FWWMRWA3O/Foundation-A3SOD99KJ0S9.pcm: No object file for requested architecture
while processing lib/ios/Expecta.framework/Expecta(EXPMatchers+beFalsy.o):
warning: /Users/yakovsh/Downloads/expecta-1.0.3/build/ModuleCache/CE2FWWMRWA3O/ObjectiveC-2CD0WTQVXITO7.pcm: No such file or directory
while processing lib/ios/Expecta.framework/Expecta(EXPMatchers+beFalsy.o):

warning: /Users/yakovsh/Downloads/expecta-1.0.3/build/ModuleCache/CE2FWWMRWA3O/ObjectiveC-2CD0WTQVXITO7.pcm: No object file for requested architecture
while processing lib/ios/Expecta.framework/Expecta(EXPMatchers+beFalsy.o):

warning: Could not resolve external type c:objc(cs)NSString
while processing lib/ios/Expecta.framework/Expecta(EXPMatchers+beFalsy.o):

**Comment by orta** [comment]
Supposedly this is a bug with Xcode: https://forums.developer.apple.com/thread/17921

**Comment by yakovsh** [comment]
The only workaround that worked for me was the one described here:

https://github.com/CocoaPods/cocoapods-packager/issues/101

It entails turning off debugging:

GCC_GENERATE_DEBUGGING_SYMBOLS = NO;

**Comment by orta** [comment]
This was merged.
