### ISSUE TITLE
Migration to ARC

### ISSUE THREAD

**Issue by StatusReport** [specta/expecta#173]
This has been already covered in #54, #60, but Expecta still runs without ARC, which makes the code more prone to memory issues and harder to maintain.

Is there any specific reason for that? I'm willing to try and do the migration.

**Comment by orta** [comment]
Hard to say, the library just pre-dates ARC I think, I wasn't around at the beginning so don't really know. Lately, I've been trying to focus expecta on stability.

**Comment by StatusReport** [comment]
Assuming that ARC leads to better stability, do you have any objections for the migration?

**Comment by orta** [comment]
Zero

**Comment by StatusReport** [comment]
Great! I'll start working on that soon :construction_worker:

**Comment by orta** [comment]
Alright, I'm willing to call that this probably isn't needed now, it would make the codebase simpler, but there isn't active development, so it's not going to help too much.
