### ISSUE TITLE
Add class information to EXPDescribeObject

### ISSUE THREAD

**Issue by manuyavuz** [specta/expecta#177]
Hi,

When a string value is received while an NSURL value expected, fail error message would be like this:

```
expected: http://myurl.com, got: http://myurl.com
```

This is because EXPDescribeObject uses `-description` method of nsobject, which prints string value of url for NSURL class. 

Would adding also class type of values be appropriate? This way, description message could be more descriptive.

I can help with a PR if this is a proper improvement for you.

**Comment by orta** [comment]
This should be in: https://github.com/specta/expecta/pull/168

Are you up to date?

**Comment by manuyavuz** [comment]
I'm using v1.0.3 coming from cocoapods. Isn't it included in that release yet? If so, I can use :head version.

**Comment by orta** [comment]
Would recommend `:head`- once #175 is in I'll do a version bump etc

**Comment by manuyavuz** [comment]
Great. 

Thx for the info @orta, and sorry for duplicate :(

**Comment by orta** [comment]
Not a problem, glad to see we had the same issue.
