### ISSUE TITLE
Forgetting brackets silently passes

### ISSUE THREAD

**Issue by jasperblues** [specta/expecta#25]
This is maybe not worth worrying about but worth mentioning: 

If you forget to put brackets at the end of a statement, like so: 

expect([hosts count] > 7).to.beTruthy;

. . then it will just pass. . 
 
(not sure how it works and/or how you'd fix it)

**Comment by orta** [comment]
Fixed by https://github.com/paulsamuels/expecta/commit/bd025bf5137d94623add075c1bd96b8ab188131c
