### ISSUE TITLE
Method Invocation With Indirect Pointer Inside expect() Triggers compiler error

### ISSUE THREAD

**Issue by segiddins** [specta/expecta#34]
```objc
NSString *input = @"http://google.com/";
    NSURL *output;
    NSError *error;
expect([transformer transformValue:input toValue:&output error:&error]).to.beTruthy();
```

Yields the compiler error `Sending 'NSURL *const __strong *' to parameter of type '__autoreleasing id *' changes retain/release properties of pointer`. Likely related to <http://developer.apple.com/library/mac/releasenotes/ObjectiveC/RN-TransitioningToARC/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011226-CH1-SW4>.

**Comment by orta** [comment]
@segiddins think this is closable?
