### ISSUE TITLE
Asserting that all objects in an NSArray are of a specific class

### ISSUE THREAD

**Issue by sibljon** [specta/expecta#70]
Is there an existing way to check that all objects in an NSArray are of a specific type?

If not, would you be open to a pull request with an interface as follows? 

Syntax:

```objc
NSArray *x; // x can be NSArray, NSSet (NSDictionary? Checking only values?)
expect(x).to.containOnlyInstancesOf([XXClass class]);
expect(x).to.containOnlyKindsOf([XXClass class]);
expect(x).to.containOnlySubclassesOf([XXClass class]);
```

Regards,
Jon

**Comment by orta** [comment]
I built a custom matcher to do this: https://github.com/orta/Expecta-ContainerClasses perhaps some of the extra ideas could be migrated into that?

**Comment by orta** [comment]
Think this can be dealt with via a custom matcher. :+1:
