### ISSUE TITLE
beNil, beTruthy, and beFalsy should not accept incorrect syntax.

### ISSUE THREAD

**Issue by benzguo** [specta/expecta#87]
It's really easy to mistakenly use the incorrect syntax with `beNil`, `beTruthy`, and `beFalsy` and end up with conditions that always pass, e.g.

```
expect(YES).to.beNil;
expect(NO).to.beTruthy;
expect(YES).to.beFalsy;
```

Some kind of warning or syntax error would be really helpful.

**Comment by orta** [comment]
closing, this is merged.
