### ISSUE TITLE
How do you explicitly fail a test?

### ISSUE THREAD

**Issue by fatuhoku** [specta/expecta#96]
I would love to see something like

```objc
fail()
```

I found [here](http://iosunittesting.com/category/xctest/) that you can just do a
```objc
XCTFail (format…)
```
but that's not every Expecta-like.

**Comment by orta** [comment]
I've taken a stab at this, opinions? https://github.com/specta/expecta/issues/96

**Comment by orta** [comment]
OK, this is in a new release has been pushed, give it a test run please.

**Comment by fatuhoku** [comment]
`failureWithError(NSError *)` would be nice!
